In [4]:
from external_models_pca import *

In [5]:
import sklearn

In [6]:
print(sklearn.__version__)

1.7.1


In [9]:
N = 100
M = 4
D = [20, 30, 40, 50]
K = 5

In [10]:
def generate_simple(K, N, M, D, noise=1):
    z = np.random.normal(size = (N, K))
    w = [np.random.normal(size = (K, D)) for m in range(M)]
    data = {'M'+str(m): np.dot(z, w[m]) + np.random.normal(size = (N,D), scale=noise) for m in range(M)}

    return data, z, w

In [11]:
data, z, w = generate_simple(K, N, M, D[0])

## PCA - no treshold on expl. var

In [12]:
mod = model_pca(data, 15, seed=123)
mod.fit()

In [13]:
model = mod.get_model()

In [14]:
mod.get_factors()

array([[ 3.51136831e+00,  1.90048654e+00,  1.17931196e+00,
        -7.87950116e+00, -3.48225378e+00, -7.56236627e-01,
        -3.40453242e-01],
       [-3.46754449e+00, -2.16673412e+00, -5.32471071e+00,
        -3.91299527e+00,  1.27060793e+00,  6.33379072e-01,
         3.78229087e-01],
       [ 7.83442901e-01,  4.13327878e+00, -4.24807506e+00,
         3.55723705e+00, -1.74569272e+00, -5.47304328e-01,
        -1.57809080e+00],
       [ 7.99495456e-02,  1.93841363e+00,  1.25998709e+00,
        -5.49201754e+00,  2.12518943e+00, -1.70115560e+00,
        -9.19166150e-01],
       [ 1.51562917e+00, -2.22208559e+00, -2.85881129e+00,
        -3.49794325e+00,  4.20958940e+00, -1.00723734e+00,
        -2.64096263e+00],
       [-6.72324333e+00, -2.05864429e-01, -5.61681702e+00,
        -2.21736751e+00,  6.52431337e+00, -1.17521423e+00,
         9.92924220e-01],
       [ 7.18008011e+00,  4.62329480e+00, -1.36519214e+00,
        -1.78784682e+00,  3.75441390e+00,  1.46256654e-01,
        -9.9500144

In [15]:
mod.get_weights()

[array([[ 1.17890373e-01, -4.03811036e-02, -1.69465269e-01,
          1.61686246e-01, -1.28366362e-02,  4.08664593e-02,
         -2.33594497e-02],
        [-9.55751648e-02, -2.09896488e-01, -5.88980202e-02,
          3.90612751e-02, -1.14862880e-01, -2.26401892e-02,
          7.31689985e-04],
        [-5.58553207e-02,  1.34246032e-02,  1.33760844e-01,
          3.10078736e-02, -4.66386190e-02,  7.68657897e-01,
          8.66587682e-02],
        [ 7.99146023e-02, -1.76692262e-01, -7.69245603e-02,
         -7.60356145e-02,  1.11019591e-01, -1.33023903e-01,
          1.57330669e-01],
        [ 1.25910183e-01,  4.27752928e-03,  1.36428889e-01,
         -1.32632481e-02, -1.95180615e-01, -2.69024703e-02,
         -1.68680315e-02],
        [-1.19465425e-01,  1.70358146e-01, -7.54346632e-02,
         -5.88697225e-02, -6.77237606e-02,  2.96794408e-02,
         -5.39860805e-02],
        [ 8.64667195e-02,  1.05257693e-01,  1.24635933e-01,
          7.71774898e-02, -9.53172089e-02, -7.63889776e-02

In [16]:
mod.variance_explained_per_factor_per_view()

array([[0.17437441, 0.16284317, 0.32042874, 0.26804003],
       [0.19687971, 0.16578117, 0.14211162, 0.19018886],
       [0.18511246, 0.15822153, 0.13696403, 0.16331047],
       [0.13457103, 0.17763589, 0.13599536, 0.07055932],
       [0.0854852 , 0.11835787, 0.0923306 , 0.1478429 ],
       [0.0362609 , 0.00579819, 0.00212434, 0.00178902],
       [0.00746946, 0.0264117 , 0.00483952, 0.00367161]])

In [17]:
mod.variance_explained_per_factor()

array([0.23142159, 0.17374034, 0.16090212, 0.1296904 , 0.11100414,
       0.01149311, 0.01059807])

In [18]:
mod.variance_explained_per_view()

array([0.82015316, 0.81504952, 0.83479422, 0.84540221])

In [19]:
mod.K_fitted

np.int64(7)

## PCA - with a treshold on expl. var

In [20]:
mod = model_pca(data, 15, seed=123, explained_variance_treshold=0.0128)
mod.fit()

In [21]:
model = mod.get_model()

In [22]:
mod.get_factors()

array([[ 3.51136831e+00,  1.90048654e+00,  1.17931196e+00,
        -7.87950116e+00, -3.48225378e+00],
       [-3.46754449e+00, -2.16673412e+00, -5.32471071e+00,
        -3.91299527e+00,  1.27060793e+00],
       [ 7.83442901e-01,  4.13327878e+00, -4.24807506e+00,
         3.55723705e+00, -1.74569272e+00],
       [ 7.99495456e-02,  1.93841363e+00,  1.25998709e+00,
        -5.49201754e+00,  2.12518943e+00],
       [ 1.51562917e+00, -2.22208559e+00, -2.85881129e+00,
        -3.49794325e+00,  4.20958940e+00],
       [-6.72324333e+00, -2.05864429e-01, -5.61681702e+00,
        -2.21736751e+00,  6.52431337e+00],
       [ 7.18008011e+00,  4.62329480e+00, -1.36519214e+00,
        -1.78784682e+00,  3.75441390e+00],
       [ 4.10581267e+00,  1.02410460e+00, -1.68928564e+00,
         2.75994427e+00, -1.44808741e+00],
       [ 7.18999528e+00, -2.55733762e-01, -3.18661442e+00,
        -4.79558711e+00, -6.80904358e-01],
       [-2.63975032e+00,  6.99461410e-02, -1.29881453e+00,
         5.39397247e+00

In [23]:
mod.get_weights()

[array([[ 0.11789037, -0.0403811 , -0.16946527,  0.16168625, -0.01283664],
        [-0.09557516, -0.20989649, -0.05889802,  0.03906128, -0.11486288],
        [-0.05585532,  0.0134246 ,  0.13376084,  0.03100787, -0.04663862],
        [ 0.0799146 , -0.17669226, -0.07692456, -0.07603561,  0.11101959],
        [ 0.12591018,  0.00427753,  0.13642889, -0.01326325, -0.19518062],
        [-0.11946542,  0.17035815, -0.07543466, -0.05886972, -0.06772376],
        [ 0.08646672,  0.10525769,  0.12463593,  0.07717749, -0.09531721],
        [ 0.11330848, -0.14135823, -0.03127923,  0.06300555, -0.14403591],
        [-0.06375087,  0.01853177, -0.0777379 , -0.24258875,  0.00890585],
        [ 0.00941953, -0.19883368,  0.00795316,  0.14233845,  0.01756031],
        [ 0.01745868, -0.03210841, -0.2228349 , -0.07843806, -0.12787242],
        [ 0.07479659,  0.05724294,  0.2100139 ,  0.06465583,  0.07025588],
        [-0.04856836, -0.14860193, -0.14306673,  0.13770688,  0.05829491],
        [-0.10147335, -0.

In [24]:
mod.variance_explained_per_factor_per_view()

array([[0.17437441, 0.16284317, 0.32042874, 0.26804003],
       [0.19687971, 0.16578117, 0.14211162, 0.19018886],
       [0.18511246, 0.15822153, 0.13696403, 0.16331047],
       [0.13457103, 0.17763589, 0.13599536, 0.07055932],
       [0.0854852 , 0.11835787, 0.0923306 , 0.1478429 ]])

In [25]:
mod.variance_explained_per_factor()

array([0.23142159, 0.17374034, 0.16090212, 0.1296904 , 0.11100414])

In [26]:
mod.variance_explained_per_view()

array([0.7764228 , 0.78283963, 0.82783036, 0.83994159])

In [27]:
mod.K_fitted

np.int64(5)

In [28]:
mod.variance_explained_total(), np.sum(mod.variance_explained_per_factor())

(array(0.80675859), np.float64(0.8067585937803752))