In [1]:
from external_models_tucker import *
import numpy as np

In [2]:
import tensorly

In [3]:
print(tensorly.__version__)

0.9.0


In [4]:
N = 100
M = 4
D = [20 for m in range(M)]
K = 5

In [5]:
def generate_simple(K, N, M, D, noise=1):
    z = np.random.normal(size = (N, K))
    w = [np.random.normal(size = (K, D)) for m in range(M)]
    data = {'M'+str(m): np.dot(z, w[m]) + np.random.normal(size = (N,D), scale=noise) for m in range(M)}

    return data, z, w

In [6]:
data, z, w = generate_simple(K, N, M, D[0])


## Tucker decomposition

In [7]:
mod = model_tucker(data, 10, seed=123)
mod.fit()

In [8]:
model = mod.get_model()

In [9]:
mod.get_factors()

array([[-1.48758762e-01, -2.20503044e-02, -3.96743871e-02,
        -7.89741165e-02, -1.05337609e-01,  1.28997749e-01,
        -1.60760741e-01],
       [ 3.13585565e-02,  1.61285680e-02,  2.23022737e-01,
         3.40843316e-02, -2.08556547e-01,  1.87182764e-01,
        -1.25680658e-02],
       [ 7.16185793e-02,  6.11850316e-02, -7.03052821e-02,
         5.01848519e-03,  6.04405975e-02,  7.09243712e-02,
         1.74043175e-01],
       [-1.22918314e-01, -5.00127216e-02, -5.92334318e-02,
         7.45342227e-02,  1.40745093e-01,  1.56862867e-01,
         9.06823352e-02],
       [-3.12779533e-02,  2.86331850e-02, -1.30825539e-02,
         1.03459104e-01, -1.49426963e-03, -2.28460352e-01,
        -2.30090567e-02],
       [-1.10829664e-01,  4.22320149e-02,  1.00399984e-01,
        -5.47058913e-02, -6.07377211e-02, -1.22641467e-01,
         1.83478337e-01],
       [-4.83534991e-02, -1.65529032e-01,  3.72858119e-02,
         1.32127392e-01,  5.30857978e-02, -2.91979230e-02,
        -1.1697696

In [10]:
mod.get_weights()

[array([[-0.39520216,  5.80013048, -4.64095236, -2.19985218,  0.75832798,
         -1.96407645,  2.25549116],
        [ 4.70467848,  2.70941347, -4.1628363 , -3.13585882,  5.57764047,
          0.99126023, -0.2804263 ],
        [-8.67328813,  2.46037906,  2.26103083, -0.02185742,  2.28507631,
          0.68660249, -0.04209475],
        [ 3.4997392 ,  5.48750602,  1.69143176,  5.25027464,  3.33121569,
          0.47623238,  0.64307658],
        [ 1.24272449, -6.23806827, -6.70437971,  1.44127687,  0.64587419,
          0.23954204, -0.14350377],
        [ 2.03560433,  6.30022993,  3.41880749, -0.95119548,  3.71583443,
         -0.76798288,  0.67020709],
        [ 2.15970328,  0.91345124,  2.83156541,  5.84100621,  0.80106275,
          0.40157763, -4.82938907],
        [-2.2064496 ,  7.53757408, -0.86175447, -0.2082053 , -1.35283394,
         -3.54359152, -0.75307528],
        [ 5.84486306, -2.64028292,  5.07591212,  4.45389033,  2.67060853,
         -0.24947251, -0.27906872],
        [ 

In [11]:
mod.variance_explained_per_factor_per_view()

array([[0.19349172, 0.26490435, 0.22330426, 0.16570317],
       [0.19583622, 0.06343473, 0.25865747, 0.2687491 ],
       [0.13911283, 0.17995639, 0.10243097, 0.15903543],
       [0.12866177, 0.17264626, 0.12257387, 0.11133717],
       [0.10294969, 0.15212644, 0.10096943, 0.09020128],
       [0.02180153, 0.00387405, 0.00819013, 0.01462964],
       [0.02114845, 0.00605633, 0.00435895, 0.00927363]])

In [12]:
mod.variance_explained_per_factor()

array([0.21185088, 0.19666938, 0.1451339 , 0.13380477, 0.11156171,
       0.01212384, 0.01020934])

In [13]:
mod.variance_explained_per_view()

array([0.80300221, 0.84299854, 0.82048509, 0.81892942])

In [14]:
mod.K_fitted

7