In [2]:
from internal_models_cling import *
import sys
sys.path.append('../')

In [3]:
N = 100
M = 4
D = [20 for m in range(M)]
K = 5

In [4]:
def generate_simple(K, N, M, D, noise=0.5):
    z = np.random.normal(size = (N, K))
    w = [np.random.normal(size = (K, D)) for m in range(M)]
    data = {'M'+str(m): np.dot(z, w[m]) + np.random.normal(size = (N,D), scale=noise) for m in range(M)}

    return data, z, w

In [ ]:
data, z, w = generate_simple(K, N, M, D[0])

## Cling - prune

In [6]:
mod = model_cling_AD(data, 10)
mod.fit()

/home/gosia/miniconda3/envs/cling_mofa/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
CLING-FA fit:   3%|███████████████████████████▊                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

[add] Added 3 factor(s); K -> 15


CLING-FA fit:   5%|█████████████████████████████████████████████████▍                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 107/2000 [00:02<00:45, 41.29it/s, ELBO=-10407.7, K=18]

[add] Added 3 factor(s); K -> 18


CLING-FA fit:   7%|█████████████████████████████████████████████████████████████████▎                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | 141/2000 [00:03<00:36, 50.77it/s, ELBO=-9691.4, K=8]

[lock] Deleted inactive → K -> 8
[prune] Deleted 10 factors; K -> 8


CLING-FA fit:   9%|███████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 172/2000 [00:03<00:24, 74.54it/s, ELBO=-9471.7, K=5]

[lock] Deleted inactive → K -> 5
[prune] Deleted 3 factors; K -> 5


CLING-FA fit:  11%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 215/2000 [00:03<00:19, 89.62it/s, ELBO=-9579.0, K=8]

[add] Added 3 factor(s); K -> 8


CLING-FA fit:  14%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 279/2000 [00:04<00:16, 105.82it/s, ELBO=-9453.1, K=5]

[lock] Deleted inactive → K -> 5
[prune] Deleted 3 factors; K -> 5


CLING-FA fit:  16%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 323/2000 [00:04<00:14, 119.35it/s, ELBO=-9549.0, K=8]

[add] Added 3 factor(s); K -> 8


CLING-FA fit:  19%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 384/2000 [00:05<00:11, 136.16it/s, ELBO=-9442.6, K=5]

[lock] Deleted inactive → K -> 5
[prune] Deleted 3 factors; K -> 5


CLING-FA fit:  22%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 433/2000 [00:05<00:10, 150.76it/s, ELBO=-9439.1, K=5]

[add] Added 3 factor(s); K -> 8
[lock] force-set K=5 → K -> 5
[lock] Two-value oscillation detected; freezing capacity at K=5 and running 50 more iterations.


CLING-FA fit:  23%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 451/2000 [00:05<00:18, 85.11it/s, ELBO=-9438.1, K=5]


Stopped after lock: ran 50 extra iterations.


In [7]:
model = mod.get_model()

In [8]:
mod.get_factors()[:5, :]

array([[ 0.62711104, -1.37757326,  0.09036177, -0.14879086, -0.1418103 ],
       [ 0.19655085,  0.56292825, -1.01844175, -0.98961487,  0.15951984],
       [ 0.94618176,  0.5943893 ,  0.31641899, -0.16888567, -0.95080767],
       [ 0.3682246 ,  0.24865775, -0.99685552,  0.85762428, -0.10298621],
       [-0.24895333,  0.32698135,  0.96776957, -0.10160948,  0.65969709]])

In [9]:
mod.get_weights()[0][:5,:]

array([[-1.21650052, -0.35391765, -1.07746953, -0.3454493 ,  0.07981427],
       [-0.67073957,  0.99482875, -0.24623121, -0.81524246, -1.01528293],
       [-0.00555944, -1.80882179,  0.43435706, -0.30375566,  1.68322217],
       [-0.17358431, -1.71503721,  0.27148978,  1.03320352,  1.00867369],
       [ 0.49314276, -2.34854547,  0.09113174,  0.46448608, -1.35535758]])

In [10]:
mod.variance_explained_per_factor_per_view()

array([[0.19591175, 0.24691035, 0.21235979, 0.38883823],
       [0.2698468 , 0.19482438, 0.23892335, 0.21229901],
       [0.16325802, 0.2436485 , 0.16121401, 0.14443423],
       [0.20995465, 0.13174174, 0.17421374, 0.12723492],
       [0.1249388 , 0.1385262 , 0.17249535, 0.09415167]])

In [11]:
mod.variance_explained_per_factor()

array([0.26809312, 0.22719276, 0.17881868, 0.15826697, 0.12927259])

In [12]:
mod.variance_explained_per_view()

array([0.96165584, 0.96309772, 0.95219641, 0.96832505])

In [13]:
mod.get_number_of_active_factors()

5