In [3]:
from external_models_muvi import *
from importlib.metadata import version
import sys
from copy import copy

In [4]:
import muvi

In [5]:
print(version('muvi'))

0.1.5


In [6]:
import mudata as mu
import anndata as ad
import torch
import numpy as np

In [7]:
print(mu.__version__)
print(ad.__version__)
print(torch.__version__)

0.2.3
0.8.0
2.3.1+cu121


In [8]:
print(sys.version) # muvi requires python < 3.11

3.10.18 (main, Jun  5 2025, 13:14:17) [GCC 11.2.0]


In [9]:
N = 100
M = 4
D = [20 for m in range(M)]
K = 5

In [10]:
def generate_simple(K, N, M, D, noise=1):
    z = np.random.normal(size = (N, K))
    w = [np.random.normal(size = (K, D)) for m in range(M)]
    data = {'M'+str(m): np.dot(z, w[m]) + np.random.normal(size = (N,D), scale=noise) for m in range(M)}

    return data, z, w

In [11]:
data, z, w = generate_simple(K, N, M, D[0])

## muVI

In [12]:
mod = model_muvi(data, 5, seed=123)
mod.fit()

2025-11-19 16:37:00,692 - muvi.core.models - INFO - Setting the name of each sample to `sample_idx`.
2025-11-19 16:37:00,694 - muvi.core.models - INFO - Setting the name of each feature in `M0` to `M0_feature_idx`.
2025-11-19 16:37:00,696 - muvi.core.models - INFO - Setting the name of each feature in `M1` to `M1_feature_idx`.
2025-11-19 16:37:00,697 - muvi.core.models - INFO - Setting the name of each feature in `M2` to `M2_feature_idx`.
2025-11-19 16:37:00,699 - muvi.core.models - INFO - Setting the name of each feature in `M3` to `M3_feature_idx`.
2025-11-19 16:37:00,701 - muvi.core.models - INFO - Likelihoods set to `{'M0': 'normal', 'M1': 'normal', 'M2': 'normal', 'M3': 'normal'}`.
2025-11-19 16:37:00,702 - muvi.core.models - INFO - NMF set to `{'M0': False, 'M1': False, 'M2': False, 'M3': False}`.
2025-11-19 16:37:00,703 - muvi.core.models - INFO - Normalizing observations.
2025-11-19 16:37:00,704 - muvi.core.models - INFO - Centering features of view `M0`.
2025-11-19 16:37:00,70

  0%|          | 0/10000 [00:00<?, ?it/s]

2025-11-19 16:37:01,687 - root - INFO - Guessed max_plate_nesting = 3


 10%|█         | 1025/10000 [00:28<04:09, 35.92it/s, ELBO=63.7]

Relative improvement of -0.002376 < 1e-05 for 10 step(s) in a row, stopping early.
2025-11-19 16:37:29,356 - muvi.core.models - INFO - Call `model._training_log` to inspect the training progress.
MODEL FIT FINE 0 
MODEL FIT FINE


In [13]:
model = mod.get_model()

In [14]:
mod.get_factors()

array([[ 1.84946322,  1.84302521,  1.22306979,  0.62948418, -0.85246897],
       [ 1.21992373,  0.1290296 , -0.59435505,  1.02359295, -0.63691127],
       [-0.32688957, -0.8593086 ,  0.29043248,  1.88056326,  0.4238418 ],
       [ 0.12247293,  0.44197607,  0.26810873,  0.31620666, -1.85301173],
       [ 1.18463564,  0.16764188, -0.25090805, -1.1074214 , -0.05785022],
       [ 1.5005722 ,  0.75821066,  0.07870235,  0.21711047,  0.05096377],
       [ 0.79176086,  1.53288651, -0.20830166, -0.50673068, -0.32762319],
       [ 0.86399609,  0.63665903, -0.75573993,  0.27381602, -1.08053672],
       [-1.36462414, -0.57313514, -1.02403307,  0.30884027, -0.1917624 ],
       [-1.07773876,  1.32164848, -0.52931464, -1.33474112,  0.53706598],
       [-0.46261701,  1.1242764 ,  0.84874028,  1.63766015, -0.1212307 ],
       [-0.20218785,  0.37660849,  0.23930478,  0.48598471, -0.2215452 ],
       [ 0.36220634, -0.42872566,  1.33138478, -1.60006678,  0.40190604],
       [ 1.50326359, -0.00861891,  0.0

In [15]:
mod.get_weights()

[array([[ 0.4885217 , -0.17703883,  0.35104138,  0.12185533,  0.70377934],
        [ 0.63440162,  0.16623487,  0.87743491,  0.40805486, -0.82867628],
        [-0.14025056, -0.2826505 ,  0.01695783,  0.60778904,  0.18358475],
        [-0.98842597, -0.39260659,  0.1523957 , -0.14454404,  0.50950927],
        [ 0.01950468, -0.12859069, -0.07478003,  1.15114403, -1.24724293],
        [-0.43490028,  0.77683789,  0.27099738,  0.53484827,  0.03042114],
        [ 0.45387793, -0.31260207,  0.55345112, -0.10228497,  0.33927247],
        [-0.61959702, -0.10688768, -0.17349741, -0.06469685, -0.59388602],
        [ 0.26235068,  0.03857598,  0.01465984, -1.3362155 ,  0.06084825],
        [-0.217833  ,  0.02926434,  0.49471638, -0.71139991, -0.15651833],
        [-0.72396839, -0.11126499,  0.10539372, -0.07805878,  0.52910167],
        [ 0.42831007, -0.83696437,  0.4095163 , -0.02481882, -0.29459575],
        [ 0.33361468,  0.43698326, -1.05928206, -0.36372501,  0.84686285],
        [-0.06222944, -0.

In [16]:
mod.variance_explained_per_factor_per_view()

array([[0.14503991, 0.15951725, 0.13619614, 0.09611857],
       [0.09866849, 0.19730731, 0.1726136 , 0.22773382],
       [0.12028223, 0.15009768, 0.20685033, 0.26565549],
       [0.27772256, 0.13109989, 0.21386913, 0.2018359 ],
       [0.26073135, 0.1807224 , 0.12072322, 0.1337357 ]])

In [17]:
muvi.tl.variance_explained(model)

2025-11-19 16:37:29,516 - muvi.tools.utils - WARNING - Cache has not yet been setup, initialising model cache.


({'M0': 0.8816160187125206,
  'M1': 0.8129311203956604,
  'M2': 0.8541770130395889,
  'M3': 0.8929821997880936},
              r2_M0     r2_M1     r2_M2     r2_M3
 factor_0  0.145040  0.159517  0.136196  0.096119
 factor_1  0.098668  0.197307  0.172614  0.227734
 factor_2  0.120282  0.150098  0.206850  0.265655
 factor_3  0.277723  0.131100  0.213869  0.201836
 factor_4  0.260731  0.180722  0.120723  0.133736,
 Empty DataFrame
 Columns: [r2_M0, r2_M1, r2_M2, r2_M3]
 Index: [])

In [18]:
mod.variance_explained_per_factor()

array([0.13421797, 0.1740808 , 0.18572143, 0.20613187, 0.17397817])

In [19]:
mod.variance_explained_per_view()

array([0.88161602, 0.81293112, 0.854177  , 0.8929822 ])

In [20]:
mod.get_number_of_active_factors()

5